name: Release
on:
  push:
    tags:
    - 'v*'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Build Artifacts
      run: |
        tar -czvf ckeditor-imageuploader.tar.gz imageUploader
    - name: Upload Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: artifacts
        path: ckeditor-imageuploader.tar.gz
  create-release:
    name: Upload
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: true
        prerelease: false
    - name: Download Artifacts
      uses: actions/download-artifact@v1
      with:
        name: artifacts
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./artifacts/ckeditor-imageuploader.tar.gz
        asset_name: ckeditor-imageuploader.tar.gz
        asset_content_type: application/tar+gzip
